server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: order
  datasource:
    # common
    url: jdbc:mysql://localhost:3306/secondkill_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  type-aliases-package: zone.medolia.goods.domain
  mapper-locations: classpath:zone/medolia/goods/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000

# redis
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 30
  password: 123456
  poolMaxTotal: 3000
  poolMaxIdle: 100
  poolMaxWait: 100
